ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
#
ENV BLYNK_HOME=/opt/blynk
#
RUN set -xe \
	&& apk add --no-cache --purge -uU curl libxrender unzip \
    && mkdir -p ${BLYNK_HOME}/data \
    && VERSION=$(curl -SL https://api.github.com/repos/blynkkk/blynk-server/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]' | sed -e 's_v__') \
    && echo "using version: ${VERSION}" > ${BLYNK_HOME}/version \
    && curl -o ${BLYNK_HOME}/blynk.jar -SL https://github.com/blynkkk/blynk-server/releases/download/v${VERSION}/server-${VERSION}-java8.jar \
    && curl -o ${BLYNK_HOME}/server.properties -SL https://raw.githubusercontent.com/blynkkk/blynk-server/master/server/core/src/main/resources/server.properties \
    && curl -o ${BLYNK_HOME}/mail.properties -SL https://raw.githubusercontent.com/blynkkk/blynk-server/master/server/notifications/email/src/main/resources/mail.properties \
    && chown -Rh alpine:alpine ${BLYNK_HOME} \
    && rm -rf /var/cache/apk/* /tmp/*
#
COPY root/ /
#
VOLUME /opt/blynk/data/
#
# IP port listing:
# 7443: Administration UI HTTPS port
# 8080: HTTP port
# 8081: Web socket ssl/tls port
# 8082: Web sockets plain tcp/ip port
# 8441: Hardware ssl/tls port (for hardware that supports SSL/TLS sockets)
# 8442: Hardware plain tcp/ip port
# 8443: Application mutual ssl/tls port
# 9443: HTTPS port
EXPOSE 7443 8080 8081 8082 8441 8442 8443 9443
#
ENTRYPOINT ["/init"]
